### ISSUE TITLE
False negative when special char is at end of local part

### ISSUE THREAD

**Issue by thomasdc** [tallesl/EmailAddressValidator#1]
According to the validator fooé@bar.com is invalid while fooée@bar.com is detected as being valid. 

Both should be valid.

**Comment by tallesl** [comment]
First, sorry for the long delay!

Yeah, the algorithm is [quick and dirty](https://github.com/tallesl/EmailAddressValidator#quick-and-dirty) alright.

I have an idea for a better validation, might get back here in a few days.

**Comment by tallesl** [comment]
Me again.

I've published a [second version of the package](https://nuget.org/packages/EmailAddressValidator/2.0.0) with a better validation. [Your both examples pass as valid now](https://github.com/tallesl/EmailAddressValidator/blob/2.0.0/EmailAddressValidator.Tests/Issue1.cs).

**Comment by thomasdc** [comment]
Cool! Thanks!
