### ISSUE TITLE
Validates emailaddress ending with '.'

### ISSUE THREAD

**Issue by thomasdc** [tallesl/EmailAddressValidator#2]
Me again :).

I've tested version 2.0, however, the following email addresses succesfully pass the validation process while they shouldn't:

con@firm.ed.
con@firm.ed...
con@firm.ed.++
con@firm.ed---
con@firm.ed--///***-test

Version 1.0 didn't validate them.

**Comment by tallesl** [comment]
Dang.

I have a _last_ idea.
Get back to you in a few days.

**Comment by tallesl** [comment]
Nope, I guess I'll leave as it this.

There's no implementation that covers all the cases (not at all), I'll be running in circles.

I thought of providing multiple implementations and letting the user pick one _à la carte_, but giving a second thought it felt like too much engineering for such a humble task.

Sorry about that and, anyway, thanks for tests cases :grinning:

**Comment by thomasdc** [comment]
Well, then I must say I prefer version 1 since that one doesn't allow the above invalid email addresses. Maybe publish version 1 of the nuget as the latest release version?

**Comment by tallesl** [comment]
Being the nice guy I am, I ended up doing the _a la carte_ thing I've mentioned before.

Version 3.0.0 has it.
