### ISSUE TITLE
How does https://github.com/jstedfast/EmailValidation fare?

### ISSUE THREAD

**Issue by jstedfast** [tallesl/EmailAddressValidator#3]
Interested to know how well https://github.com/jstedfast/EmailValidation fares in these tests.

**Comment by jstedfast** [comment]
FWIW, the MailAddressParser logic from the referencesource repository is a lot more sophisticated than you generally need for validating an email address since it also has to parse the display name, etc.

I actually did a review of it here: http://jeffreystedfast.blogspot.com/2015/03/code-review-microsofts-systemnetmail.html :)

**Comment by tallesl** [comment]
Thank you for such a careful pull request and sorry for taking so long to merge it!

**Comment by jstedfast** [comment]
No worries, and thanks for accepting/merging :)
